import type { ToolDefinition, ToolId } from "@/lib/zezinho/tools/types";

/**
 * Registro estático do catálogo de ferramentas — dado puro, versionado em código (decisão do
 * usuário, item 2). O planejador (`planner/selectTools.ts`, `planner/contextBuilder.ts`) consulta
 * isto para decidir o que chamar; o dispatcher (`executor.ts`) usa o `id` para saber qual service
 * real invocar. Os metadados `relevance`/`latencyHint`/`freshnessRequirement`/`optional`/
 * `fallbackAllowed` foram adicionados na Sprint 4.0 (Z3, seção 5) para orientar seletividade —
 * nenhuma ferramenta nova aqui inventa dado: `unanswered_clients`, `agenda_summary` e
 * `marketing_summary` sempre retornam `not_configured` porque a integração real (WhatsApp,
 * agenda, Meta Ads/Instagram) ainda não existe (Fase B, não iniciada).
 */
export const TOOL_REGISTRY: Record<ToolId, ToolDefinition> = {
  situational_context: {
    id: "situational_context",
    label: "Contexto situacional (horário de funcionamento, estágio do dia)",
    source: "Contexto situacional",
    reuses: "computeSituationalContext (src/lib/zezinho/situational/stage.ts)",
    objectives: ["business_health", "staffing_capacity"],
    requiresPeriod: false,
    costHint: "low",
    relevance: "high",
    latencyHint: "instant",
    freshnessRequirement: "realtime",
    optional: false,
    fallbackAllowed: false,
  },
  jumppark_period_summary: {
    id: "jumppark_period_summary",
    label: "Resumo operacional (JumpPark)",
    source: "JumpPark",
    reuses: "fetchOperationalOrders + computeOperationalSummary (src/lib/integrations/jumppark/operations-summary.ts)",
    objectives: ["increase_ticket", "improve_service_mix", "increase_revenue", "evaluate_pricing", "staffing_capacity", "improve_cash_flow", "business_health"],
    requiresPeriod: true,
    costHint: "medium",
    relevance: "high",
    latencyHint: "medium",
    freshnessRequirement: "realtime",
    optional: false,
    fallbackAllowed: true,
  },
  jumppark_wash_packages: {
    id: "jumppark_wash_packages",
    label: "Distribuição Bronze/Silver/Gold (JumpPark)",
    source: "JumpPark",
    reuses: "computeWashCategoryGroups (src/lib/integrations/jumppark/wash-grouping.ts)",
    objectives: ["improve_service_mix"],
    requiresPeriod: true,
    costHint: "medium",
    relevance: "medium",
    latencyHint: "medium",
    freshnessRequirement: "realtime",
    optional: true,
    fallbackAllowed: true,
  },
  cash_ledger_totals: {
    id: "cash_ledger_totals",
    label: "Entradas/saídas de caixa (Neon)",
    source: "Neon — fluxo de caixa",
    reuses: "fetchCashLedger (src/lib/finance/service.ts)",
    objectives: ["reduce_costs", "improve_cash_flow", "business_health"],
    requiresPeriod: true,
    costHint: "low",
    relevance: "high",
    latencyHint: "fast",
    freshnessRequirement: "realtime",
    optional: false,
    fallbackAllowed: true,
  },
  dre_result: {
    id: "dre_result",
    label: "Resultado gerencial (DRE, Neon)",
    source: "Neon — DRE gerencial",
    reuses: "fetchDreReport (src/lib/finance/service.ts)",
    objectives: ["business_health"],
    requiresPeriod: true,
    costHint: "medium",
    relevance: "medium",
    latencyHint: "medium",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  crm_customers: {
    id: "crm_customers",
    label: "Clientes (CRM)",
    source: "CRM (JumpPark + Contas a Receber)",
    reuses: "fetchCrmCustomers (src/lib/crm/service.ts)",
    objectives: ["client_retention"],
    requiresPeriod: false,
    costHint: "medium",
    relevance: "high",
    latencyHint: "medium",
    freshnessRequirement: "recent",
    optional: false,
    fallbackAllowed: true,
  },
  inventory_overview: {
    id: "inventory_overview",
    label: "Panorama de estoque",
    source: "Estoque",
    reuses: "fetchInventoryOverview (src/lib/inventory/service.ts)",
    objectives: [],
    requiresPeriod: false,
    costHint: "low",
    relevance: "high",
    latencyHint: "fast",
    freshnessRequirement: "recent",
    optional: false,
    fallbackAllowed: true,
  },
  central_alerts: {
    id: "central_alerts",
    label: "Alertas consolidados",
    source: "Central de Operações",
    reuses: "fetchCentralOverview + computeConsolidatedAlerts (src/lib/operations/central.ts)",
    objectives: ["business_health"],
    requiresPeriod: false,
    costHint: "high",
    relevance: "high",
    latencyHint: "slow",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  full_period_comparison: {
    id: "full_period_comparison",
    label: "Comparação completa de dois períodos",
    source: "JumpPark + Neon (fluxo de caixa + DRE)",
    reuses: "buildComparisonReport (src/lib/zezinho/comparison-engine.ts)",
    objectives: [],
    requiresPeriod: true,
    costHint: "high",
    relevance: "high",
    latencyHint: "slow",
    freshnessRequirement: "realtime",
    optional: false,
    fallbackAllowed: false,
  },
  weather_forecast: {
    id: "weather_forecast",
    label: "Previsão do tempo (condição atual, próximas horas e próximos dias)",
    source: "OpenWeatherMap",
    reuses: "getWeatherForecast (src/lib/integrations/weather/service.ts)",
    objectives: ["increase_revenue", "staffing_capacity", "business_health"],
    requiresPeriod: false,
    costHint: "low",
    relevance: "medium",
    latencyHint: "medium",
    freshnessRequirement: "any",
    optional: true,
    fallbackAllowed: true,
  },
  goal_progress: {
    id: "goal_progress",
    label: "Progresso da meta (percentual, ritmo, projeção, faixas de prêmio)",
    source: "Metas (Neon)",
    reuses: "fetchActiveGoal + computeGoalProgress (src/lib/goals/service.ts) + fetchOperationalOrders para o valor atual",
    objectives: ["increase_revenue", "business_health"],
    requiresPeriod: false,
    costHint: "medium",
    relevance: "high",
    latencyHint: "medium",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  historical_pattern: {
    id: "historical_pattern",
    label: "Padrão histórico (mesmo dia da semana, até o mesmo horário)",
    source: "JumpPark — padrão histórico",
    reuses: "fetchOperationalOrders + computeHistoricalPattern (src/lib/integrations/jumppark/historical-pattern.ts)",
    objectives: ["increase_revenue", "staffing_capacity", "business_health"],
    requiresPeriod: false,
    costHint: "medium",
    relevance: "medium",
    latencyHint: "medium",
    freshnessRequirement: "any",
    optional: true,
    fallbackAllowed: true,
  },
  accounts_payable: {
    id: "accounts_payable",
    label: "Contas a Pagar (pendente, vencido, próximos vencimentos)",
    source: "Neon — Contas a Pagar",
    reuses: "fetchAccountsPayableOverview (src/lib/finance/service.ts)",
    objectives: ["improve_cash_flow", "business_health"],
    requiresPeriod: false,
    costHint: "low",
    relevance: "medium",
    latencyHint: "fast",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  accounts_receivable: {
    id: "accounts_receivable",
    label: "Contas a Receber (a receber hoje/semana/mês, atraso)",
    source: "Neon — Contas a Receber",
    reuses: "fetchAccountsReceivableDashboard (src/lib/finance/service.ts)",
    objectives: ["improve_cash_flow", "business_health"],
    requiresPeriod: false,
    costHint: "low",
    relevance: "medium",
    latencyHint: "fast",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  unanswered_clients: {
    id: "unanswered_clients",
    label: "Conversas sem resposta (WhatsApp) — ainda não configurado",
    source: "Mensageria (WhatsApp)",
    reuses: "nenhum — integração planejada para Fase B, não iniciada",
    objectives: [],
    requiresPeriod: false,
    costHint: "low",
    relevance: "low",
    latencyHint: "instant",
    freshnessRequirement: "any",
    optional: true,
    fallbackAllowed: true,
  },
  agenda_summary: {
    id: "agenda_summary",
    label: "Agenda do dia — ainda não integrada (hoje só há dado ilustrativo)",
    source: "Agenda",
    reuses: "nenhum — /agenda hoje usa dado mock, nunca usado nas respostas do Zézinho",
    objectives: [],
    requiresPeriod: false,
    costHint: "low",
    latencyHint: "instant",
    relevance: "low",
    freshnessRequirement: "any",
    optional: true,
    fallbackAllowed: true,
  },
  marketing_summary: {
    id: "marketing_summary",
    label: "Desempenho de marketing (Meta Ads/Instagram) — ainda não configurado",
    source: "Marketing (Meta Ads/Instagram)",
    reuses: "nenhum — integração planejada para Fase B, não iniciada",
    objectives: [],
    requiresPeriod: false,
    costHint: "low",
    relevance: "low",
    latencyHint: "instant",
    freshnessRequirement: "any",
    optional: true,
    fallbackAllowed: true,
  },
  stone_reconciliation_summary: {
    id: "stone_reconciliation_summary",
    label: "Conciliação financeira Stone (vendas, recebimentos, cancelamentos, chargebacks, posição processada)",
    source: "Stone — Conciliação Cliente Stone",
    reuses: "buildReconciliationSummary (src/lib/integrations/stone/reconciliationSummary.ts)",
    objectives: ["improve_cash_flow", "business_health"],
    // O arquivo é por dia único (nunca um intervalo) — usa periodA.to ou "ontem" por padrão,
    // nunca "hoje": o arquivo do dia D só é publicado às 5h do dia D+1. Mesmo padrão de
    // `historical_pattern`/`goal_progress` (período opcional, com um default honesto quando ausente).
    requiresPeriod: false,
    costHint: "medium",
    relevance: "high",
    latencyHint: "medium",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  stone_financial_schedule: {
    id: "stone_financial_schedule",
    label: "Agenda Financeira (previsto vs. liquidado, curva de recebimentos 7/30 dias)",
    source: "Stone — Conciliação Cliente Stone (Agenda Financeira própria do Santa Monica OS)",
    reuses: "buildFinancialScheduleForToday (src/lib/integrations/stone/financialScheduleService.ts)",
    objectives: ["improve_cash_flow", "business_health"],
    // Sempre ancorada em "hoje" (periodA.to como override) — busca uma janela de dias passados
    // internamente (financialScheduleService.ts), nunca um único dia só.
    requiresPeriod: false,
    costHint: "high",
    relevance: "high",
    latencyHint: "slow",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
  stone_jumppark_reconciliation: {
    id: "stone_jumppark_reconciliation",
    label: "Conciliação Stone × JumpPark (correspondências e divergências entre vendas)",
    source: "Stone × JumpPark",
    reuses: "reconcileStoneWithJumpparkForPeriod (src/lib/integrations/stone/jumpparkReconciliationService.ts)",
    objectives: ["improve_cash_flow", "business_health"],
    requiresPeriod: true,
    costHint: "high",
    relevance: "high",
    latencyHint: "slow",
    freshnessRequirement: "recent",
    optional: true,
    fallbackAllowed: true,
  },
};
