import {
  LayoutDashboard,
  Droplets,
  ParkingSquare,
  CalendarDays,
  Users,
  Wallet,
  Megaphone,
  Boxes,
  ShoppingCart,
  ShieldCheck,
  Bot,
  Settings,
  ClipboardList,
  Receipt,
  FileMinus,
  BookOpen,
  FileBarChart,
  Tags,
  Lock,
  BellRing,
  Package,
  History,
  ClipboardCheck,
  FlaskConical,
  Beaker,
  Map,
  AlertCircle,
  ShoppingBag,
  ListChecks,
  ArrowLeftRight,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  href: string;
  label: string;
  icon: LucideIcon;
}

export const navItems: NavItem[] = [
  { href: "/dashboard", label: "Central de Operações", icon: LayoutDashboard },
  { href: "/operacoes", label: "Movimentações", icon: ClipboardList },
  { href: "/lavacao", label: "Lavação", icon: Droplets },
  { href: "/estacionamento", label: "Estacionamento", icon: ParkingSquare },
  { href: "/agenda", label: "Agenda", icon: CalendarDays },
  { href: "/clientes", label: "Clientes", icon: Users },
  { href: "/financeiro", label: "Financeiro", icon: Wallet },
  { href: "/financeiro/fluxo-de-caixa", label: "Fluxo de Caixa", icon: BookOpen },
  { href: "/financeiro/contas-a-receber", label: "Contas a Receber", icon: Receipt },
  { href: "/financeiro/contas-a-pagar", label: "Contas a Pagar", icon: FileMinus },
  { href: "/financeiro/dre", label: "DRE Gerencial", icon: FileBarChart },
  { href: "/financeiro/classificacao", label: "Classificação Financeira", icon: Tags },
  { href: "/financeiro/fechamento", label: "Fechamento", icon: Lock },
  { href: "/alertas", label: "Alertas", icon: BellRing },
  { href: "/marketing", label: "Marketing", icon: Megaphone },
  { href: "/estoque", label: "Estoque", icon: Boxes },
  { href: "/estoque/produtos", label: "Produtos", icon: Package },
  { href: "/estoque/movimentacoes", label: "Movimentações de Estoque", icon: History },
  { href: "/estoque/contagem", label: "Contagem física", icon: ClipboardCheck },
  { href: "/estoque/receitas", label: "Receitas", icon: FlaskConical },
  { href: "/estoque/calibracao", label: "Calibração", icon: Beaker },
  { href: "/estoque/mapeamentos", label: "Mapeamentos", icon: Map },
  { href: "/estoque/ordens", label: "Ordens JumpPark", icon: ListChecks },
  { href: "/estoque/consumos", label: "Consumos de Estoque", icon: ArrowLeftRight },
  { href: "/estoque/pendencias", label: "Pendências do Estoque", icon: AlertCircle },
  { href: "/estoque/compras-sugeridas", label: "Compras Sugeridas", icon: ShoppingBag },
  { href: "/compras", label: "Compras", icon: ShoppingCart },
  { href: "/seguranca", label: "Segurança", icon: ShieldCheck },
  { href: "/zezinho", label: "Zézinho IA", icon: Bot },
  { href: "/configuracoes", label: "Configurações", icon: Settings },
];
