import {
  LayoutDashboard,
  Wrench,
  Gauge,
  Droplets,
  ParkingSquare,
  CalendarDays,
  Wallet,
  Megaphone,
  Boxes,
  ShoppingCart,
  ShieldCheck,
  Bot,
  Settings,
  ClipboardList,
  Receipt,
  FileMinus,
  BookOpen,
  FileBarChart,
  Tags,
  Lock,
  BellRing,
  Package,
  History,
  ClipboardCheck,
  FlaskConical,
  Beaker,
  Map,
  AlertCircle,
  SearchCheck,
  ShoppingBag,
  ListChecks,
  ArrowLeftRight,
  Landmark,
  Radio,
  Sparkles,
  CalendarClock,
  Contact,
  PackagePlus,
  PackageMinus,
  TrendingDown,
  FileText,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  href: string;
  label: string;
  icon: LucideIcon;
}

export const navItems: NavItem[] = [
  { href: "/dashboard", label: "Central de Operações", icon: LayoutDashboard },
  { href: "/atendimento", label: "Atendimento", icon: Wrench },
  { href: "/operacao", label: "Operação ao Vivo", icon: Radio },
  { href: "/assistente-gerente", label: "Assistente do Gerente", icon: Sparkles },
  { href: "/planejamento", label: "Planejamento Operacional", icon: CalendarClock },
  { href: "/crm", label: "CRM Inteligente", icon: Contact },
  { href: "/painel-gerencial", label: "Painel Gerencial", icon: Gauge },
  { href: "/ordens", label: "Central de Ordens", icon: FileText },
  { href: "/movimentacoes", label: "Movimentações", icon: ClipboardList },
  { href: "/lavacao", label: "Lavação", icon: Droplets },
  { href: "/estacionamento", label: "Estacionamento", icon: ParkingSquare },
  { href: "/agenda", label: "Agenda", icon: CalendarDays },
  { href: "/financeiro", label: "Financeiro", icon: Wallet },
  { href: "/financeiro/fluxo-de-caixa", label: "Fluxo de Caixa", icon: BookOpen },
  { href: "/financeiro/contas-a-receber", label: "Contas a Receber", icon: Receipt },
  { href: "/financeiro/contas-a-pagar", label: "Contas a Pagar", icon: FileMinus },
  { href: "/financeiro/despesas", label: "Despesas (gerencial)", icon: TrendingDown },
  { href: "/financeiro/dre", label: "DRE Gerencial", icon: FileBarChart },
  { href: "/financeiro/classificacao", label: "Classificação Financeira", icon: Tags },
  { href: "/financeiro/fechamento", label: "Fechamento", icon: Lock },
  { href: "/financeiro/stone-conciliacao", label: "Stone Conciliação", icon: Landmark },
  { href: "/alertas", label: "Alertas", icon: BellRing },
  { href: "/marketing", label: "Marketing", icon: Megaphone },
  { href: "/estoque", label: "Estoque", icon: Boxes },
  { href: "/estoque/produtos", label: "Produtos", icon: Package },
  { href: "/estoque/entradas", label: "Entradas", icon: PackagePlus },
  { href: "/estoque/saidas", label: "Saídas", icon: PackageMinus },
  { href: "/estoque/movimentacoes", label: "Movimentações de Estoque", icon: History },
  { href: "/estoque/contagem", label: "Contagem física", icon: ClipboardCheck },
  { href: "/estoque/receitas", label: "Receitas", icon: FlaskConical },
  { href: "/estoque/calibracao", label: "Calibração", icon: Beaker },
  { href: "/estoque/mapeamentos", label: "Mapeamentos", icon: Map },
  { href: "/estoque/ordens", label: "Ordens JumpPark", icon: ListChecks },
  { href: "/estoque/consumos", label: "Consumos de Estoque", icon: ArrowLeftRight },
  { href: "/estoque/pendencias", label: "Pendências do Estoque", icon: AlertCircle },
  { href: "/estoque/compras-sugeridas", label: "Compras Sugeridas", icon: ShoppingBag },
  { href: "/estoque/auditoria", label: "Auditoria do Estoque", icon: SearchCheck },
  { href: "/compras", label: "Pesquisa de Preços (demo)", icon: ShoppingCart },
  { href: "/seguranca", label: "Segurança", icon: ShieldCheck },
  { href: "/zezinho", label: "Zézinho IA", icon: Bot },
  { href: "/configuracoes", label: "Configurações", icon: Settings },
];
