/**
 * Fixture derivada da documentação oficial (estrutura confirmada contra o exemplo "Arquivo
 * completo - Layout 2.4", https://conciliacao.stone.com.br/reference/arquivo-completo-layout-24-1)
 * — nunca dado de produção. Todo identificador é anonimizado/inventado para o teste (NSU,
 * autorização, terminal, código de estabelecimento, conta bancária) — nenhum dado sensível real.
 *
 * Cobre, num único arquivo: débito à vista, crédito à vista, crédito parcelado (3x) com
 * chargeback + estorno de chargeback numa das parcelas, uma venda com cancelamento, uma
 * antecipação (FinancialTransactionsAccounts), um repasse bancário liquidado (Payments) e uma
 * posição de carteira (WalletPosition, Layout 2.4).
 */
export const OFFICIAL_SAMPLE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<Conciliation>
  <Header>
    <GenerationDateTime>20260723053000</GenerationDateTime>
    <StoneCode>900000001</StoneCode>
    <LayoutVersion>2.4</LayoutVersion>
    <FileId>1</FileId>
    <ReferenceDate>20260722</ReferenceDate>
  </Header>
  <FinancialTransactions>
    <Transaction>
      <Events><CancellationCharges>0</CancellationCharges><Cancellation>0</Cancellation><Captures>1</Captures><ChargebackRefunds>0</ChargebackRefunds><Chargebacks>0</Chargebacks><Payments>1</Payments></Events>
      <AcquirerTransactionKey>NSU-ANON-0001</AcquirerTransactionKey>
      <InitiatorTransactionKey>INIT-ANON-0001</InitiatorTransactionKey>
      <AuthorizationDateTime>20260722100000</AuthorizationDateTime>
      <CaptureLocalDateTime>20260722100005</CaptureLocalDateTime>
      <International>false</International>
      <AccountType>1</AccountType>
      <InstallmentType>1</InstallmentType>
      <NumberOfInstallments>1</NumberOfInstallments>
      <AuthorizedAmount>100.00</AuthorizedAmount>
      <CapturedAmount>100.00</CapturedAmount>
      <CanceledAmount>0</CanceledAmount>
      <AuthorizationCurrencyCode>986</AuthorizationCurrencyCode>
      <IssuerAuthorizationCode>AUTH0001</IssuerAuthorizationCode>
      <BrandId>1</BrandId>
      <CardNumber>411111******0001</CardNumber>
      <Poi><PoiType>1</PoiType><SerialNumber>TERM-ANON-01</SerialNumber></Poi>
      <EntryMode>1</EntryMode>
      <Installments>
        <Installment><InstallmentNumber>1</InstallmentNumber><GrossAmount>100.00</GrossAmount><NetAmount>97.50</NetAmount><PrevisionPaymentDate>20260723</PrevisionPaymentDate><MdrAmount>2.50</MdrAmount></Installment>
      </Installments>
    </Transaction>
    <Transaction>
      <Events><CancellationCharges>0</CancellationCharges><Cancellation>0</Cancellation><Captures>1</Captures><ChargebackRefunds>0</ChargebackRefunds><Chargebacks>0</Chargebacks><Payments>1</Payments></Events>
      <AcquirerTransactionKey>NSU-ANON-0002</AcquirerTransactionKey>
      <InitiatorTransactionKey>INIT-ANON-0002</InitiatorTransactionKey>
      <AuthorizationDateTime>20260722110000</AuthorizationDateTime>
      <CaptureLocalDateTime>20260722110005</CaptureLocalDateTime>
      <International>false</International>
      <AccountType>2</AccountType>
      <InstallmentType>1</InstallmentType>
      <NumberOfInstallments>1</NumberOfInstallments>
      <AuthorizedAmount>200.00</AuthorizedAmount>
      <CapturedAmount>200.00</CapturedAmount>
      <CanceledAmount>0</CanceledAmount>
      <AuthorizationCurrencyCode>986</AuthorizationCurrencyCode>
      <IssuerAuthorizationCode>AUTH0002</IssuerAuthorizationCode>
      <BrandId>2</BrandId>
      <CardNumber>555555******0002</CardNumber>
      <Poi><PoiType>1</PoiType><SerialNumber>TERM-ANON-01</SerialNumber></Poi>
      <EntryMode>1</EntryMode>
      <Installments>
        <Installment><InstallmentNumber>1</InstallmentNumber><GrossAmount>200.00</GrossAmount><NetAmount>194.00</NetAmount><PrevisionPaymentDate>20260723</PrevisionPaymentDate><MdrAmount>6.00</MdrAmount></Installment>
      </Installments>
    </Transaction>
    <Transaction>
      <Events><CancellationCharges>0</CancellationCharges><Cancellation>0</Cancellation><Captures>1</Captures><ChargebackRefunds>1</ChargebackRefunds><Chargebacks>1</Chargebacks><Payments>1</Payments></Events>
      <AcquirerTransactionKey>NSU-ANON-0003</AcquirerTransactionKey>
      <InitiatorTransactionKey>INIT-ANON-0003</InitiatorTransactionKey>
      <AuthorizationDateTime>20260722120000</AuthorizationDateTime>
      <CaptureLocalDateTime>20260722120005</CaptureLocalDateTime>
      <International>false</International>
      <AccountType>2</AccountType>
      <InstallmentType>2</InstallmentType>
      <NumberOfInstallments>3</NumberOfInstallments>
      <AuthorizedAmount>300.00</AuthorizedAmount>
      <CapturedAmount>300.00</CapturedAmount>
      <CanceledAmount>0</CanceledAmount>
      <AuthorizationCurrencyCode>986</AuthorizationCurrencyCode>
      <IssuerAuthorizationCode>AUTH0003</IssuerAuthorizationCode>
      <BrandId>2</BrandId>
      <CardNumber>555555******0003</CardNumber>
      <Poi><PoiType>4</PoiType></Poi>
      <EntryMode>81</EntryMode>
      <Installments>
        <Installment><InstallmentNumber>1</InstallmentNumber><GrossAmount>100.00</GrossAmount><NetAmount>97.00</NetAmount><PrevisionPaymentDate>20260723</PrevisionPaymentDate><MdrAmount>3.00</MdrAmount></Installment>
        <Installment>
          <InstallmentNumber>2</InstallmentNumber><GrossAmount>100.00</GrossAmount><NetAmount>97.00</NetAmount><PrevisionPaymentDate>20260822</PrevisionPaymentDate><MdrAmount>3.00</MdrAmount>
          <Chargeback><PaymentId>PAY-ANON-02</PaymentId><Id>CB-ANON-01</Id><Amount>97.00</Amount><Date>20260725</Date><ChargeDate>20260726</ChargeDate><ReasonCode>4853</ReasonCode></Chargeback>
        </Installment>
        <Installment>
          <InstallmentNumber>3</InstallmentNumber><GrossAmount>100.00</GrossAmount><NetAmount>97.00</NetAmount><PrevisionPaymentDate>20260922</PrevisionPaymentDate><MdrAmount>3.00</MdrAmount>
          <ChargebackRefund><PaymentId>PAY-ANON-03</PaymentId><Id>CBR-ANON-01</Id><Amount>97.00</Amount><Date>20260728</Date><PaymentDate>20260729</PaymentDate><ReasonCode>0</ReasonCode></ChargebackRefund>
        </Installment>
      </Installments>
    </Transaction>
    <Transaction>
      <Events><CancellationCharges>0</CancellationCharges><Cancellation>1</Cancellation><Captures>1</Captures><ChargebackRefunds>0</ChargebackRefunds><Chargebacks>0</Chargebacks><Payments>1</Payments></Events>
      <AcquirerTransactionKey>NSU-ANON-0004</AcquirerTransactionKey>
      <InitiatorTransactionKey>INIT-ANON-0004</InitiatorTransactionKey>
      <AuthorizationDateTime>20260722130000</AuthorizationDateTime>
      <CaptureLocalDateTime>20260722130005</CaptureLocalDateTime>
      <International>false</International>
      <AccountType>1</AccountType>
      <InstallmentType>1</InstallmentType>
      <NumberOfInstallments>1</NumberOfInstallments>
      <AuthorizedAmount>50.00</AuthorizedAmount>
      <CapturedAmount>50.00</CapturedAmount>
      <CanceledAmount>50.00</CanceledAmount>
      <AuthorizationCurrencyCode>986</AuthorizationCurrencyCode>
      <IssuerAuthorizationCode>AUTH0004</IssuerAuthorizationCode>
      <BrandId>171</BrandId>
      <CardNumber>606282******0004</CardNumber>
      <Poi><PoiType>1</PoiType><SerialNumber>TERM-ANON-02</SerialNumber></Poi>
      <EntryMode>1</EntryMode>
      <Cancellations>
        <Cancellation><PaymentId>PAY-ANON-04</PaymentId><OperationKey>OP-ANON-01</OperationKey><CancellationDateTime>20260722140000</CancellationDateTime><ReturnedAmount>50.00</ReturnedAmount></Cancellation>
      </Cancellations>
      <Installments>
        <Installment><InstallmentNumber>1</InstallmentNumber><GrossAmount>50.00</GrossAmount><NetAmount>0.00</NetAmount><MdrAmount>0.00</MdrAmount></Installment>
      </Installments>
    </Transaction>
  </FinancialTransactions>
  <FinancialEvents>
    <Event><EventId>EVT-ANON-01</EventId><Description>Liquidação</Description><Type>10</Type><PrevisionPaymentDate>20260723</PrevisionPaymentDate><Amount>97.50</Amount></Event>
  </FinancialEvents>
  <FinancialTransactionsAccounts>
    <Transaction>
      <Events><CancellationCharges>0</CancellationCharges><Cancellation>0</Cancellation><Captures>1</Captures><ChargebackRefunds>0</ChargebackRefunds><Chargebacks>0</Chargebacks><Payments>1</Payments></Events>
      <AcquirerTransactionKey>NSU-ANON-0003</AcquirerTransactionKey>
      <InitiatorTransactionKey>INIT-ANON-0003</InitiatorTransactionKey>
      <AuthorizationDateTime>20260722120000</AuthorizationDateTime>
      <CaptureLocalDateTime>20260722120005</CaptureLocalDateTime>
      <Poi><PoiType>4</PoiType></Poi>
      <Installments>
        <Installment>
          <InstallmentNumber>1</InstallmentNumber><GrossAmount>100.00</GrossAmount><NetAmount>95.50</NetAmount><PaymentDate>20260723</PaymentDate>
          <AdvanceRateAmount>1.50</AdvanceRateAmount><AdvancedReceivableOriginalPaymentDate>20260822</AdvancedReceivableOriginalPaymentDate><PaymentId>PAY-ANON-01</PaymentId>
        </Installment>
      </Installments>
    </Transaction>
  </FinancialTransactionsAccounts>
  <Payments>
    <Payment>
      <Id>PAY-ANON-01</Id>
      <WalletTypeId>3</WalletTypeId>
      <TotalAmount>397.50</TotalAmount>
      <FavoredBankAccount><BankCode>0341</BankCode><BankBranch>0001</BankBranch><BankAccountNumber>999999</BankAccountNumber></FavoredBankAccount>
    </Payment>
  </Payments>
  <WalletPosition>
    <Wallets>
      <Wallet><WalletTypeId>3</WalletTypeId><WalletNatureId>1</WalletNatureId><Category>Default</Category><Amount>5000.00</Amount></Wallet>
    </Wallets>
  </WalletPosition>
  <Trailer>
    <CapturedTransactionsQuantity>4</CapturedTransactionsQuantity>
    <CanceledTransactionsQuantity>1</CanceledTransactionsQuantity>
    <PaidInstallmentsQuantity>6</PaidInstallmentsQuantity>
    <ChargedCancellationsQuantity>0</ChargedCancellationsQuantity>
    <ChargebacksQuantity>1</ChargebacksQuantity>
    <ChargebacksRefundQuantity>1</ChargebacksRefundQuantity>
    <ChargedChargebacksQuantity>0</ChargedChargebacksQuantity>
    <PaidChargebacksRefundQuantity>0</PaidChargebacksRefundQuantity>
    <PaidEventsQuantity>1</PaidEventsQuantity>
    <ChargedEventsQuantity>0</ChargedEventsQuantity>
  </Trailer>
</Conciliation>`;
